# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExUkfUaxhLfJo72A7uUYFALuFLFcv8V8
"""

# Commented out IPython magic to ensure Python compatibility.
# # pip install streamlit
# %%writefile app.py

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, train_test_split

# App Title
st.title("Diabetes Prediction System")
st.write("Based on the Pima Indians Diabetes Dataset")

# --- LOAD DATA & TRAIN MODEL ---
@st.cache_resource
def train_model():
    # Loading dataset (Ensure diabetes.csv is in your GitHub)
    df = pd.read_csv('diabetes.csv')
    x = df.iloc[:,:-1]
    y = df.iloc[:,-1]

    # Train/Test Split (Matching your notebook parameters)
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.35, random_state=42)

    # Logistic Regression with GridSearch (From your notebook)
    LogisticModel = LogisticRegression()
    param_grid = {
        "C": [0.001, 0.01, 0.1, 1, 10, 100],
        "penalty": ["l1", "l2"],
        "solver": ["liblinear", "saga"]
    }
    myModel = GridSearchCV(LogisticModel, param_grid, cv=10, scoring='accuracy')
    myModel.fit(x_train, y_train)
    return myModel

model = train_model()

# --- USER INPUT SIDEBAR ---
st.sidebar.header("Enter Patient Data")
preg = st.sidebar.number_input("Pregnancies", 0, 20, 3)
glucose = st.sidebar.slider("Glucose", 0, 200, 120)
bp = st.sidebar.slider("Blood Pressure", 0, 140, 70)
skin = st.sidebar.slider("Skin Thickness", 0, 100, 20)
insulin = st.sidebar.slider("Insulin", 0, 850, 80)
bmi = st.sidebar.number_input("BMI", 0.0, 70.0, 25.0)
dpf = st.sidebar.number_input("Diabetes Pedigree Function", 0.0, 2.5, 0.5)
age = st.sidebar.slider("Age", 1, 100, 30)

# --- PREDICTION ---
if st.button("Predict"):
    features = np.array([[preg, glucose, bp, skin, insulin, bmi, dpf, age]])
    prediction = model.predict(features)

    if prediction[0] == 1:
        st.error("The model predicts: **DIABETIC**")
    else:
        st.success("The model predicts: **NOT DIABETIC**")