# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExUkfUaxhLfJo72A7uUYFALuFLFcv8V8
"""

pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Page Config
st.set_page_config(page_title="Diabetes Prediction", layout="wide")

st.title("Diabetes Prediction System")
st.write("This app uses a Support Vector Machine (SVM) model to predict diabetes.")

# --- STEP 1: LOAD DATA ---
@st.cache_data # This keeps the app fast by not reloading data on every click
def load_data():
    df = pd.read_csv('diabetes.csv')
    return df

try:
    diabetes_dataset = load_data()

    # --- STEP 2: TRAIN MODEL ---
    X = diabetes_dataset.drop(columns='Outcome', axis=1)
    Y = diabetes_dataset['Outcome']

    scaler = StandardScaler()
    scaler.fit(X)
    standardized_data = scaler.transform(X)
    X = standardized_data

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

    classifier = svm.SVC(kernel='linear')
    classifier.fit(X_train, Y_train)

    # --- STEP 3: USER INTERFACE ---
    col1, col2 = st.columns(2)

    with col1:
        st.header("Input Patient Data")
        preg = st.number_input("Pregnancies", 0, 20, 1)
        glucose = st.number_input("Glucose", 0, 200, 120)
        bp = st.number_input("Blood Pressure", 0, 150, 70)
        skin = st.number_input("Skin Thickness", 0, 100, 20)
        insulin = st.number_input("Insulin", 0, 900, 80)
        bmi = st.number_input("BMI", 0.0, 70.0, 25.0)
        dpf = st.number_input("Diabetes Pedigree Function", 0.0, 2.5, 0.5)
        age = st.number_input("Age", 1, 120, 30)

        if st.button("Predict"):
            input_data = (preg, glucose, bp, skin, insulin, bmi, dpf, age)
            input_as_numpy = np.asarray(input_data).reshape(1, -1)
            std_data = scaler.transform(input_as_numpy)
            prediction = classifier.predict(std_data)

            if prediction[0] == 0:
                st.success("The person is **not diabetic**.")
            else:
                st.error("The person **is diabetic**.")

    with col2:
        st.header("Data Visualization")
        fig, ax = plt.subplots()
        sns.histplot(diabetes_dataset['Glucose'], kde=True, ax=ax)
        ax.set_title("Glucose Distribution")
        st.pyplot(fig)

except FileNotFoundError:
    st.error("Error: 'diabetes.csv' not found. Please upload it to your GitHub repository.")