# -*- coding: utf-8 -*-
"""Diabetesdetect

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11y-85zYGr9fT6ayzKdi09I5pKBxesrTt
"""

# Import the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Load the datasets of the person data
df=pd.read_csv('/content/diabetes.csv')

df.head()

df.info()

# identify the independant and dependant features
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

# Perform the train_test split on the following records of the datasets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.35,random_state=42)

# so the model will be based on the classification based
# Applying the logistic regression analysis
from sklearn.linear_model import LogisticRegression
# Define a model of it
LogisticModel=LogisticRegression()
# Import the Grid Search Cv
from sklearn.model_selection import GridSearchCV
param_grid = {
    "C": [0.001, 0.01, 0.1, 1, 10, 100],  # Regularization strength
    "penalty": ["l1", "l2"],              # Regularization type
    "solver": ["liblinear", "saga"]       # Solvers supporting L1 + L2
}
myModel=GridSearchCV(LogisticModel,param_grid,cv=10,scoring='accuracy')
myModel.fit(x_train,y_train)

# Test the accuracy of this model
y_pred=myModel.predict(x_test)

y_pred

# Test the accuracy score of the following model
from sklearn.metrics import accuracy_score,classification_report
print("Accuracy Score is: ",accuracy_score(y_test,y_pred)*100,"%")

# Apply the decision tree model to improve the model
from sklearn.tree import DecisionTreeClassifier
decisionTreeModel=DecisionTreeClassifier()
# Apply the grid search cv
from sklearn.model_selection import GridSearchCV
param_grid = {
    "criterion": ["gini", "entropy", "log_loss"],   # Splitting criteria
    "max_depth": [None, 3, 5, 7, 10],           # Controls tree depth
    "min_samples_split": [2, 5, 10, 20]  ,          # Min samples to split a node
    "min_samples_leaf": [1, 2, 5, 10]          # Min samples per leaf node
    # "max_features": [None, "sqrt", "log2"]          # Feature selection at each split
}
myNewModel=GridSearchCV(decisionTreeModel,param_grid,cv=10,scoring='accuracy')
myNewModel.fit(x_train,y_train)

y_pred=myNewModel.predict(x_test)

y_pred

# Now Test the accuracy score of it
print("Accuracy Score: ",accuracy_score(y_test,y_pred)*100,"%")

# Now lets predict the diabetes for the other users
x.info()

pregnancies = int(input("Enter number of Pregnancies: "))
glucose = int(input("Enter Glucose level: "))
blood_pressure = int(input("Enter Blood Pressure: "))
skin_thickness = int(input("Enter Skin Thickness: "))
insulin = int(input("Enter Insulin level: "))
bmi = float(input("Enter BMI: "))
dpf = float(input("Enter Diabetes Pedigree Function: "))
age = int(input("Enter Age: "))

new_data={
    'Pregnancies':[pregnancies],
    'Glucose':[glucose],
    'BloodPressure':[blood_pressure],
    'SkinThickness':[skin_thickness],
    'Insulin':[insulin],
    'BMI':[bmi],
    'DiabetesPedigreeFunction':[dpf],
    'Age':[age]
}

df1=pd.DataFrame(new_data)

df1

pred_yes_no=myNewModel.predict(df1)

pred_yes_no

if(pred_yes_no[0]==1):
    print("You have a diabetes")
else:
    print("You Are Normal")