# -*- coding: utf-8 -*-
"""FIr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuMumf9AjGHf6ATnxaFjOtpVvAyGzmAB
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("My Streamlit App")
# st.write("Hello, *World!* :sunglasses:")
#

!npm install localtunnel

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &

# !streamlit run app.py &>/content/logs.txt &
!npm localtunnel --port 8501

!curl ipv4.icanhazip.com